### ISSUE TITLE
Not Authorized

### ISSUE THREAD

**Issue by JacopKane** [gregavola/tumblrPHP#2]
Im getting 

``` JSON
{"meta":{"status":401,"msg":"Not Authorized"},"response":[]}
```

response with both

``` PHP
$followers = $tumblr->oauth_post("/blog/tumbil.tumblr.com/followers");
```

or 

``` PHP
$followers = $tumblr->oauth_get("/blog/tumbil.tumblr.com/followers");
```

This is happening after authorization and everything is same with example. Couldn't figure it out.

**Comment by gregavola** [comment]
Can you post your code? You need to be authenticated to use this method.

Thanks,

Greg Avola
http://gregavola.me

e: gregory.avola@gmail.com

**Comment by gorillaradio** [comment]
Hello I have the same problem. My code is your index.php
I just entered my consumer and secret and then changed your blog url to mine.

**Comment by JacopKane** [comment]
Sorry btw, i switched another solution of mine so couldn't sent a fiddle.

**Comment by dannyhtek** [comment]
Well there is a reason why you should not copy+paste any code without rechecking every single line. The problem you guys are having is the following line in the callback.php:

$followers = $tumblr->oauth_get("/blog/blog.untappd.com/followers");
print_r($followers);

Basically what you guys are trying to do is printing the followerslist of 'blog.untappd.com' while the blog hasn't signed in to your application. You have no permissions to do that. So here's the fix:

I run a blog (dannyhtek.tumblr.com) and thats also where I'm hosting my applications. After signing in and approving my own app, I get redirected to my callback.php and everything works fine, Why? Because I approved the app with MY tumblr and I'm requesting the followerslist of MY tumblr, using  the following line:

$followers = $tumblr->oauth_get("/blog/dannyhtek.tumblr.com/followers");

You see the difference? You obviously can not request the followerlist of a blog who hasnt signed in to your application as your application has no permissions to do that.
